language: android
jdk: oraclejdk8
android:
  components:
  - platform-tool
  - build-tools-23.0.1
  - android-23
  - extra
notifications:
  email: true
cache:
  apt: true
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
    - ${TRAVIS_BUILD_DIR}/android-sdk/extras/

env:
  global:
    - GRADLE_USER_HOME=${TRAVIS_BUILD_DIR}/gradle
    - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
    - SDK=${TRAVIS_BUILD_DIR}/android-sdk
    - PATH=${GRADLE_USER_HOME}/bin/:${SDK}/:${SDK}/tools/:${SDK}/platform-tools/:${PATH}

before_install:
  - echo "WARNING delete this when fixed"; export OLD_SDK=/usr/local/android-sdk-23.0.1;
                                           mkdir -p ${SDK};
                                           cp -u -R ${OLD_SDK}/platforms ${SDK}/platforms;
                                           cp -u -R ${OLD_SDK}/system-images ${SDK}/system-images;
                                           cp -u -R ${OLD_SDK}/tools ${SDK}/tools || echo "CP ERROR"
script:
- "./gradlew test"
before_deploy: "./gradlew assemble"
deploy:
  provider: releases
  api_key:
    secure: sJscVrGRUt6Fa8AoXRbJ1z1VNlTaPdK78getTM2NN8kRcFtaeaTyfdV4ldX3AmG1jXzbwHAeC028EMgrTnMpkjTnwXYE8ARTQJ1vhW2FAqFLBNXw7LGTtjxsmbwo2jF9CC1PAg44FsbY7QGGsJE6b2NF9/YHdci2hP1R+9UjyCMn60kZO6YM6hL8j3us8G2VI2UV4W7qp8m4ddr1wmNmenQZMX7vOpt3AF683/jAiYK3BNMPGnzridM+MSSypJ6xVLBsvhlDjT+qDH6zAFE6qZp0XFZfk1V38P5dZ+LBWzdqbqWy5PoP+dxySIgRcV5jMhybx+qxEp/bMF2n4zK/UNsZyrhgYjY575OzJDPzRiAQYefJPfJiD7F8D0ibxUrj1NeLTQxFe0r/NQw5bNFBB17ukNQ1kfW7iuRZMsS6Ddh1Qip622e+ixgElLnYhLdaQrq+elIfnHQTrOiqg/jdRzPlCNIbj+j03xVXyEgoUGUxjBaUIhPq8TrPCzgYgsvS4iJoecQ+TSX+XLqu3EEpxJSVBlghEBlOkdhBmGb6kBDdn/ztm3B39kI6uNe/NtYyJ1HUGUkJxK19dxV22tt9LImVRgxHPWuxkyLaOSPhoYwpvDnpIaLU9fiSY+1AOjs840Usowg4alH+q0JgyxxowKBmpQ7yirJrtuzSudCy7nA=
  file: app/build/outputs/apk/app-release-unsigned.apk
  file_glob: "true"
  skip_cleanup: true
  on:
    repo: alabeduarte/mypodcasts-android
    branch: master
after_success:
- sh ./ci/set_tags.sh
- sh ./ci/release.sh